<a href="https://colab.research.google.com/github/vrushikesh123/statml-b40/blob/main/statml_assign_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('/content/breast_cancer_survival.csv')
data.head()

Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0   42  FEMALE   0.95256   2.15000  0.007972 -0.048340           II   
1   54  FEMALE   0.00000   1.38020 -0.498030 -0.507320           II   
2   63  FEMALE  -0.52303   1.76400 -0.370190  0.010815           II   
3   78  FEMALE  -0.87618   0.12943 -0.370380  0.132190            I   
4   42  FEMALE   0.22611   1.74910 -0.543970 -0.390210           II   

                       Histology ER status PR status HER2 status Surgery_type  \
0  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
1  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
2  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   Lumpectomy   
3  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
4  Infiltrating Ductal Carcinoma  Positive  Positive    Positive   Lumpectomy   

  Date_of_Surgery Date_of_Last_Visit Patient_Status  
0       20-May-18          26-Aug-18          Alive  
1       26-Apr-18          25-Jan-19           Dead  
2       24-Aug-18          08-Apr-20          Alive  
3       16-Nov-18          28-Jul-20          Alive  
4       12-Dec-18          05-Jan-19          Alive

In [5]:
dataf = pd.DataFrame(data)
dataf.head()

Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0   42  FEMALE   0.95256   2.15000  0.007972 -0.048340           II   
1   54  FEMALE   0.00000   1.38020 -0.498030 -0.507320           II   
2   63  FEMALE  -0.52303   1.76400 -0.370190  0.010815           II   
3   78  FEMALE  -0.87618   0.12943 -0.370380  0.132190            I   
4   42  FEMALE   0.22611   1.74910 -0.543970 -0.390210           II   

                       Histology ER status PR status HER2 status Surgery_type  \
0  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
1  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
2  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   Lumpectomy   
3  Infiltrating Ductal Carcinoma  Positive  Positive    Negative        Other   
4  Infiltrating Ductal Carcinoma  Positive  Positive    Positive   Lumpectomy   

  Date_of_Surgery Date_of_Last_Visit Patient_Status  
0       20-May-18          26-Aug-18          Alive  
1       26-Apr-18          25-Jan-19           Dead  
2       24-Aug-18          08-Apr-20          Alive  
3       16-Nov-18          28-Jul-20          Alive  
4       12-Dec-18          05-Jan-19          Alive

In [6]:
dataf.dtypes

Age                     int64
Gender                 object
Protein1              float64
Protein2              float64
Protein3              float64
Protein4              float64
Tumour_Stage           object
Histology              object
ER status              object
PR status              object
HER2 status            object
Surgery_type           object
Date_of_Surgery        object
Date_of_Last_Visit     object
Patient_Status         object
dtype: object

In [7]:
dataf.columns

Index(['Age', 'Gender', 'Protein1', 'Protein2', 'Protein3', 'Protein4',
       'Tumour_Stage', 'Histology', 'ER status', 'PR status', 'HER2 status',
       'Surgery_type', 'Date_of_Surgery', 'Date_of_Last_Visit',
       'Patient_Status'],
      dtype='object')

In [8]:
for column in dataf.columns:
    if dataf[column].dtype == 'object':
        unique_values = dataf[column].unique()
        #print(f"Unique values in column '{column}': {unique_values}")
        dataf[column] = dataf[column].map({value: index for index, value in enumerate(unique_values)})

In [9]:
dataf.head()

Age  Gender  Protein1  Protein2  Protein3  Protein4  Tumour_Stage  \
0   42       0   0.95256   2.15000  0.007972 -0.048340             0   
1   54       0   0.00000   1.38020 -0.498030 -0.507320             0   
2   63       0  -0.52303   1.76400 -0.370190  0.010815             0   
3   78       0  -0.87618   0.12943 -0.370380  0.132190             1   
4   42       0   0.22611   1.74910 -0.543970 -0.390210             0   

   Histology  ER status  PR status  HER2 status  Surgery_type  \
0          0          0          0            0             0   
1          0          0          0            0             0   
2          0          0          0            0             1   
3          0          0          0            0             0   
4          0          0          0            1             1   

   Date_of_Surgery  Date_of_Last_Visit  Patient_Status  
0                0                   0               0  
1                1                   1               1  
2                2                   2               0  
3                3                   3               0  
4                4                   4               0

In [10]:
x0 = 1
x1 = dataf['Age']
x2 = dataf['Protein1']
x3 = dataf['Protein2']
x4 = dataf['Protein3']
x5 = dataf['Protein4']
x6 = dataf['Tumour_Stage']
x7 = dataf['Histology']
x8 = dataf['ER status']
x9 = dataf['PR status']
x10 = dataf['HER2 status']
x11 = dataf['Surgery_type']
x12 = dataf['Date_of_Surgery']
x13 = dataf['Date_of_Last_Visit']

#For target-Variable.
y = dataf['Patient_Status']

In [11]:
x_array = np.array(list(zip(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13)))
y_array = np.array(y)

In [12]:
x_array

array([[ 42.     ,   0.95256,   2.15   , ...,   0.     ,   0.     ,
          0.     ],
       [ 54.     ,   0.     ,   1.3802 , ...,   0.     ,   1.     ,
          1.     ],
       [ 63.     ,  -0.52303,   1.764  , ...,   1.     ,   2.     ,
          2.     ],
       ...,
       [ 54.     ,   0.75382,   1.6425 , ...,   3.     ,  84.     ,
        283.     ],
       [ 74.     ,   0.97251,   1.4268 , ...,   1.     ,  10.     ,
        284.     ],
       [ 66.     ,   0.28638,   1.3998 , ...,   2.     , 117.     ,
        285.     ]])

In [13]:
y_array

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 2, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [14]:
y_array[y_array == '2'] = 0

In [15]:
y_array

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 2, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [16]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 334 non-null    int64  
 1   Gender              334 non-null    int64  
 2   Protein1            334 non-null    float64
 3   Protein2            334 non-null    float64
 4   Protein3            334 non-null    float64
 5   Protein4            334 non-null    float64
 6   Tumour_Stage        334 non-null    int64  
 7   Histology           334 non-null    int64  
 8   ER status           334 non-null    int64  
 9   PR status           334 non-null    int64  
 10  HER2 status         334 non-null    int64  
 11  Surgery_type        334 non-null    int64  
 12  Date_of_Surgery     334 non-null    int64  
 13  Date_of_Last_Visit  334 non-null    int64  
 14  Patient_Status      334 non-null    int64  
dtypes: float64(4), int64(11)
memory usage: 39.3 KB


In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

for i in [0.3, 0.4, 0.5]:
    X_train, X_test, y_train, y_test = train_test_split(x_array, y_array, test_size=i, random_state=42)

    # Initialize the KNN model (k = 5)
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train, y_train)

    # Make prediction
    y_pred = knn.predict(X_test)

    #Now, calculate Accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for test size {i*100:.0f}%: {accuracy*100:.2f}")

Accuracy for test size 30%: 72.28
Accuracy for test size 40%: 74.63
Accuracy for test size 50%: 74.85


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

test_sizes = [0.2, 0.25, 0.3, 0.35]

for test_size in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(x_array, y_array, test_size=test_size, random_state=42)

    svm = SVC(kernel='linear')
    svm.fit(X_train, y_train)

    #make Predicition.
    y_pred = svm.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for test size {test_size*100:.0f}%: {accuracy*100:.2f}")